# configmap untuk menyimpan konfigurasi env yang sifatnya tidak rahasia
# secret utuk menyipan konfigurasi yang sifat nya sensitif misal kek pass dll
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-secret-key
type: Opaque
stringData:
  password: KONTOL
  apiKey: hehehehe-bangsad-anda
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config-map
data:
  version: v1.0.4
  env: development
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      name: nodejs-app
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-env
          image: khannedy/nodejs-env
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-config-map
            - secretRef:
                name: nodejs-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-servie
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
  - port: 8080
    targetPort: 3000
    nodePort: 30301


