apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: "sharing-volume"
        operator: In
        values:
          - "yes"
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        sharing-volume: "yes"
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: nodejs-writer
          image: khannedy/nodejs-writer
          volumeMounts:
            - name: html
              mountPath: /app/html
        - name: nginx
          image: nginx
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx
    sharing-volume: "yes"
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001